const points = [
  {
    id: 1,
    order_route: 1,
    name: "Sztab Marszałka Piłsudskiego 1920",
    era: "WOJNA 1920",
    type: "OBIEKT HISTORYCZNY / ARCHITEKTURA",
    addr: "ul. Marszałka Piłsudskiego",
    coords: [22.60789, 51.46234],
    audio: "audio_sztab_pilsudskiego_1920.mp3",
    bohater_naglowek: "Marszałek Józef Piłsudski",
    bohater_kafelek: "Naczelny Wódz Wojska Polskiego, twórca niepodległego państwa polskiego i zwycięski dowódca w wojnie polsko-bolszewickiej 1920 roku."
  },
  {
    id: 2,
    order_route: 2,
    name: "Tablica Wojska Polskiego 1920",
    era: "WOJNA 1920",
    type: "POMNIK / TABLICA",
    addr: "Rynek 15 (Fasada Kościoła)",
    coords: [22.6075, 51.4628],
    audio: "audio_tablica_wojska_polskiego_1920.mp3",
    bohater_naglowek: "Żołnierze Wojny Polsko-Bolszewickiej 1920",
    bohater_kafelek: "Bohaterowie walk o niepodległość Polski, którzy powstrzymali nawałę bolszewicką na przedpolach Lubartowa w sierpniu 1920 roku."
  },
  {
    id: 3,
    order_route: 3,
    name: "Siedziba Gestapo i Żandarmerii",
    era: "II WOJNA SWIATOWA",
    type: "OBIEKT HISTORYCZNY / KATOWNIA",
    addr: "ul. Cmentarna 4",
    coords: [22.6091, 51.4615],
    audio: "audio_siedziba_gestapo_i_zandarmerii.mp3",
    bohater_naglowek: "Ofiary Okupacji Niemieckiej",
    bohater_kafelek: "Mieszkańcy ziemi lubartowskiej więzieni, torturowani i mordowani przez niemieckie gestapo i żandarmerię w latach 1939–1944."
  },
  {
    id: 4,
    order_route: 4,
    name: "Więzienie Gestapo i Katownia UB",
    era: "II WOJNA SWIATOWA",
    type: "OBIEKT HISTORYCZNY / KATOWNIA",
    addr: "ul. Słowackiego 7",
    coords: [22.6083, 51.4632],
    audio: "audio_wiezienie_gestapo_i_katownia_ub.mp3",
    bohater_naglowek: "Aresztowani Żołnierze AK i WiN",
    bohater_kafelek: "Niezłomni bohaterowie podziemia niepodległościowego, poddawani brutalnym przesłuchaniom przez niemieckie Gestapo, a po 1944 roku przez komunistyczny UB."
  },
  {
    id: 5,
    order_route: 5,
    name: "Dawny Szpital Polowy AK",
    era: "II WOJNA SWIATOWA",
    type: "OBIEKT HISTORYCZNY / MEDYCYNA",
    addr: "ul. Legionów 2",
    coords: [22.6062, 51.4619],
    audio: "audio_dawny_szpital_polowy_ak.mp3",
    bohater_naglowek: "Sanitariuszki i Lekarze AK",
    bohater_kafelek: "Personel medyczny Podziemia, który z narażeniem życia ratował rannych partyzantów i żołnierzy Armii Krajowej."
  },
  {
    id: 6,
    order_route: 6,
    name: "Dom Przejściowy Wołyniaków",
    era: "II WOJNA SWIATOWA",
    type: "MIEJSCE PAMIECI / SCHRONIENIE",
    addr: "ul. Lubelska 34",
    coords: [22.6055, 51.4608],
    audio: "audio_dom_przejsciowy_wolyniakow.mp3",
    bohater_naglowek: "Uchodźcy i Przesiedleńcy z Wołynia",
    bohater_kafelek: "Polacy ocaleni z rzezi wołyńskiej, którzy znaleźli bezpieczne schronienie i pomoc medyczną u mieszkańców Lubartowa."
  },
  {
    id: 7,
    order_route: 7,
    name: "Punkt Kontaktowy 27 WDP AK",
    era: "II WOJNA SWIATOWA",
    type: "MIEJSCE PAMIECI / CONSPIRACY",
    addr: "ul. Cicha 8",
    coords: [22.6041, 51.4621],
    audio: "audio_punkt_kontaktowy_27_wdp_ak.mp3",
    bohater_naglowek: "Łączniczki i Kurierzy 27 WDP AK",
    bohater_kafelek: "Cisi bohaterowie konspiracji, zapewniający łączność, przepływ rozkazów i meldunków dla oddziałów Wołyńskiej Dywizji Piechoty."
  },
  {
    id: 8,
    order_route: 8,
    name: "Kryjówka Żołnierzy Wyklętych",
    era: "OKRES POWOJENNY",
    type: "OBIEKT HISTORYCZNY / CONSPIRACY",
    addr: "ul. Poprzeczna 12",
    coords: [22.6098, 51.4641],
    audio: "audio_kryjowka_zolnierzy_wykletych.mp3",
    bohater_naglowek: "Żołnierze Niezłomni / Wyklęci",
    bohater_kafelek: "Bohaterowie powojennego oporu antykomunistycznego, ukrywający się przed bezpieką w podziemnych schronach i melinach."
  },
  {
    id: 9,
    order_route: 9,
    name: "Posterunek MO i Urząd Bezpieczeństwa",
    era: "OKRES POWOJENNY",
    type: "OBIEKT HISTORYCZNY / REPRESJE",
    addr: "ul. Lipowa 3",
    coords: [22.6105, 51.4612],
    audio: "audio_posterunek_mo_i_urzad_bezpieczenstwa.mp3",
    bohater_naglowek: "Ofiary Terroru Komunistycznego",
    bohater_kafelek: "Więzieni i prześladowani działacze niepodległościowi oraz mieszkańcy powiatu lubartowskiego po opanowaniu Polski przez reżim stalinowski."
  },
  {
    id: 10,
    order_route: 10,
    name: "Pomnik Niepodległości",
    era: "PAMIEC OGOLNA",
    type: "POMNIK / MIEJSCE PAMIECI",
    addr: "Plac Wolności 1",
    coords: [22.6071, 51.4625],
    audio: "audio_pomnik_niepodleglosci.mp3",
    bohater_naglowek: "Obrońcy Ojczyzny Wszystkich Epok",
    bohater_kafelek: "Kolejne pokolenia mieszkańców Lubartowa walczących o wolną i niepodległą Polskę na przestrzeni wieków."
  },
  {
    id: 11,
    order_route: 11,
    name: "Drukarnia Podziemna AK",
    era: "II WOJNA SWIATOWA",
    type: "MIEJSCE PAMIECI / PRASA PODZIEMNA",
    addr: "ul. Partyzantów 15",
    coords: [22.6032, 51.4638],
    audio: "audio_drukarnia_podziemna_ak.mp3",
    bohater_naglowek: "sierż. Karol Skaruch ps. „Warta”",
    bohater_kafelek: "Drukarz i wydawca podziemnej gazety „Świt”, niosący prawdę i nadzieję mieszkańcom w najciemniejszych latach okupacji."
  },
  {
    id: 12,
    order_route: 12,
    name: "Siedziba Sztabu BCh",
    era: "II WOJNA SWIATOWA",
    type: "OBIEKT HISTORYCZNY / DOWODZTWO",
    addr: "ul. Kościuszki 20",
    coords: [22.6088, 51.4601],
    audio: "audio_siedziba_sztabu_bch.mp3",
    bohater_naglowek: "Żołnierze Batalionów Chłopskich",
    bohater_kafelek: "Bohaterowie ruchu ludowego, obrońcy wsi polskiej i partyzanci walczący ramie w ramię z AK przeciwko okupantowi."
  },
  {
    id: 13,
    order_route: 13,
    name: "Mogiła Powstańców Styczniowych 1863",
    era: "POWSTANIE STYCZNIOWE",
    type: "NEKROPOLIA / MOGIŁA",
    addr: "Cmentarza Parafialny",
    coords: [22.6112, 51.4595],
    audio: "audio_mogila_powstancow_styczniowych_1863.mp3",
    bohater_naglowek: "Powstańcy Styczniowi 1863 r.",
    bohater_kafelek: "Bohaterowie zrywu narodowego przeciwko carskiemu zaborcy, którzy oddali życie na ziemi lubartowskiej."
  },
  {
    id: 14,
    order_route: 14,
    name: "Kwatera Żołnierzy AK i Września 1939",
    era: "II WOJNA SWIATOWA",
    type: "NEKROPOLIA / KWATERA WOJSKOWA",
    addr: "Cmentarz Parafialny",
    coords: [22.6118, 51.4592],
    audio: "audio_kwatera_zolnierzy_ak_i_wrzesnia_1939.mp3",
    bohater_naglowek: "Polegli Żołnierze Września i AK",
    bohater_kafelek: "Obrońcy Polski z września 1939 roku oraz polegli w walkach i egzekucjach partyzanci Obwodu AK Lubartów."
  },
  {
    id: 15,
    order_route: 15,
    name: "Symboliczny Grobowiec Żołnierzy Wyklętych",
    era: "OKRES POWOJENNY",
    type: "NEKROPOLIA / SYMBOLICZNY POMNIK",
    addr: "Cmentarz Parafialny",
    coords: [22.6121, 51.4589],
    audio: "audio_symboliczny_grobowiec_zolnierzy_wykletych.mp3",
    bohater_naglowek: "por. Zdzisław Broński ps. „Uskok”",
    bohater_kafelek: "Legendarny dowódca oddziałów partyzanckich AK-WiN na Lubelszczyźnie, symbol bezkompromisowej walki o Wolną Polskę."
  },
  {
    id: 16,
    order_route: 16,
    name: "Schron Wojskowy i Magazyn Broni",
    era: "II WOJNA SWIATOWA",
    type: "OBIEKT MILITARNY / SCHRON",
    addr: "ul. Nowa 5",
    coords: [22.6021, 51.4645],
    audio: "audio_schron_wojskowy_i_magazyn_broni.mp3",
    bohater_naglowek: "Kwatermistrze i Zbrojmistrze AK",
    bohater_kafelek: "Ludzie odpowiedzialni za gromadzenie, konserwację i wydawanie broni dla oddziałów partyzanckich udających się na akcje."
  },
  {
    id: 17,
    order_route: 17,
    name: "Punkt Zrzutowy Broni",
    era: "II WOJNA SWIATOWA",
    type: "MIEJSCE PAMIECI / OPERACJA LOTNICZA",
    addr: "ul. Polna 18",
    coords: [22.5985, 51.4662],
    audio: "audio_punkt_zrzutowy_broni.mp3",
    bohater_naglowek: "Cichociemni i Placówki Odbiorcze",
    bohater_kafelek: "Bohaterowie odbierający zrzuty alianckie z wielkiej Brytanii, przyjmujący zasobniki z bronią, amunicją i sprzętem radiowym."
  },
  {
    id: 18,
    order_route: 18,
    name: "Miejsce Egzekucji Cywilów 1943",
    era: "II WOJNA SWIATOWA",
    type: "MIEJSCE PAMIECI / MARTYROLOGIA",
    addr: "ul. Piaskowa 2",
    coords: [22.6141, 51.4629],
    audio: "audio_miejsce_egzekucji_cywilow_1943.mp3",
    bohater_naglowek: "Rozstrzelani Mieszkańcy Lubartowa",
    bohater_kafelek: "Niewinne ofiary niemieckich represji i odwetów publicznych rozstrzeliwane w odwecie za podziemne akcje sabotażowe."
  },
  {
    id: 19,
    order_route: 19,
    name: "Dom Pamięci Ochotników 1920",
    era: "WOJNA 1920",
    type: "OBIEKT HISTORYCZNY / PAMIĘĆ",
    addr: "ul. Krótka 1",
    coords: [22.6068, 51.4635],
    audio: "audio_dom_pamieci_ochotnikow_1920.mp3",
    bohater_naglowek: "Ochotnicy Ziemi Lubartowskiej 1920",
    bohater_kafelek: "Młodzież, uczniowie i mieszkańcy, którzy dobrowolnie wstąpili do Armii Ochotniczej gen. Józefa Hallera."
  },
  {
    id: 20,
    order_route: 20,
    name: "Apteka Podziemna i Punkt Opatrunkowy",
    era: "II WOJNA SWIATOWA",
    type: "OBIEKT HISTORYCZNY / SANITARIAT",
    addr: "ul. Rynek 8",
    coords: [22.6073, 51.4625],
    audio: "audio_apteka_podziemna_i_punkt_opatrunkowy.mp3",
    bohater_naglowek: "kpt. dr Zbigniew Bartków",
    bohater_kafelek: "Żołnierz Armii Krajowej, harcmistrz ZHP oraz lekarz niosący pomoc medyczną partyzantom w warunkach konspiracji."
  },
  {
    id: 21,
    order_route: 21,
    name: "Siedziba Tajnego Nauczania",
    era: "II WOJNA SWIATOWA",
    type: "OBIEKT HISTORYCZNY / EDUKACJA",
    addr: "ul. Cmentarna 18",
    coords: [22.6102, 51.4605],
    audio: "audio_siedziba_tajnego_nauczania.mp3",
    bohater_naglowek: "ks. Aleksander Szulc ps. „Ina”",
    bohater_kafelek: "Nauczyciele i tajni edukatorzy, którzy z narażeniem życia prowadzili zabronioną przez Niemców edukację młodzieży."
  },
  {
    id: 22,
    order_route: 22,
    name: "Lokal Kontaktowy WiN",
    era: "OKRES POWOJENNY",
    type: "OBIEKT HISTORYCZNY / CONSPIRACY",
    addr: "ul. Ogrodowa 4",
    coords: [22.6049, 51.4611],
    audio: "audio_lokal_kontaktowy_win.mp3",
    bohater_naglowek: "Działacze Zrzeszenia „Wolność i Niezawisłość”",
    bohater_kafelek: "Konspiratorzy cywilni i wojskowi kontynuujący opór przeciw sowieckiej dominacji po rozwiązaniu Armii Krajowej."
  },
  {
    id: 23,
    order_route: 23,
    name: "Dawne Gimnazjum - Ośrodek Oporu",
    era: "II WOJNA SWIATOWA",
    type: "OBIEKT HISTORYCZNY / SZKOLNICTWO",
    addr: "ul. Lubelska 10",
    coords: [22.6061, 51.4615],
    audio: "audio_dawne_gimnazjum_osrodek_oporu.mp3",
    bohater_naglowek: "Profesorowie i Uczniowie Tajnych Kompletów",
    bohater_kafelek: "Młodzież gimnazjalna tworząca szare szeregi i mały sabotaż w oporze przeciwko germanizacji."
  },
  {
    id: 24,
    order_route: 24,
    name: "Warsztat Krawiecki - Kryjówka Służb",
    era: "II WOJNA SWIATOWA",
    type: "OBIEKT HISTORYCZNY / CONSPIRACY",
    addr: "ul. Szewska 3",
    coords: [22.6081, 51.4618],
    audio: "audio_warsztat_krawiecki_kryjowka_sluzb.mp3",
    bohater_naglowek: "Krawcy i Rzemieślnicy w Konspiracji",
    bohater_kafelek: "Mieszkańcy tworzący podwójne ściany, skrytki na broń oraz szyjący mundury dla oddziałów leśnych."
  },
  {
    id: 25,
    order_route: 25,
    name: "Krzyż Pamięci Powstańców 1863",
    era: "POWSTANIE STYCZNIOWE",
    type: "POMNIK / MIEJSCE PAMIECI",
    addr: "Rondo Styczniowe",
    coords: [22.6155, 51.4601],
    audio: "audio_krzysz_pamieci_powstancow_1863.mp3",
    bohater_naglowek: "Dowódcy i Oddziały Powstańcze 1863 r.",
    bohater_kafelek: "Upamiętnienie miejsca starć i zaciętych potyczek z wojskami carskimi na obrzeżach Lubartowa."
  },
  {
    id: 26,
    order_route: 26,
    name: "Punkt Odbioru Radiowego Sztabu",
    era: "II WOJNA SWIATOWA",
    type: "MIEJSCE PAMIECI / ŁĄCZNOŚĆ",
    addr: "ul. Słowackiego 12",
    coords: [22.6089, 51.4639],
    audio: "audio_punkt_odbioru_radiowego_sztabu.mp3",
    bohater_naglowek: "Radiooperatorzy i Łącznościowcy AK",
    bohater_kafelek: "Obsługa tajnych radiostacji odbierających wiadomości z Rządu Polskiego na Uchodźstwie w Londynie."
  },
  {
    id: 27,
    order_route: 27,
    name: "Tablica por. Bolesław Mucharski ps. „Lekarz”",
    era: "II WOJNA SWIATOWA",
    type: "MIEJSCE PAMIECI / TABLICA",
    addr: "ul. Cmentarna 10",
    coords: [22.6095, 51.4609],
    audio: "audio_tablica_boleslaw_mucharski.mp3",
    bohater_naglowek: "por. Bolesław Mucharski ps. „Lekarz”",
    bohater_kafelek: "Dowódca Oddziału Partyzanckiego Armii Krajowej w Obwodzie Lubartowskim, walczący z okupantem w latach 1941–1945, zamordowany na Zamku Lubelskim."
  },
  {
    id: 28,
    order_route: 28,
    name: "Tablica kpt. dr Zbigniew Bartków",
    era: "II WOJNA SWIATOWA",
    type: "MIEJSCE PAMIECI / TABLICA",
    addr: "Rynek 20",
    coords: [22.6073, 51.4625],
    audio: "audio_tablica_zbigniew_bartkow.mp3",
    bohater_naglowek: "kpt. dr Zbigniew Bartków",
    bohater_kafelek: "Żołnierz Armii Krajowej, harcmistrz ZHP oraz lekarz niosący pomoc medyczną partyzantom i ludności w warunkach konspiracji."
  },
  {
    id: 29,
    order_route: 29,
    name: "Mural 27 WDP AK (RCEZ)",
    era: "II WOJNA SWIATOWA",
    type: "MURAL / MIEJSCE PAMIECI",
    addr: "ul. 1 Maja 82",
    coords: [22.6000, 51.4620],
    audio: "audio_mural_27_wdp_ak.mp3",
    bohater_naglowek: "27 Wołyńska Dywizja Piechoty AK",
    bohater_kafelek: "Największy w Polsce mural poświęcony 27. Wołyńskiej Dywizji Piechoty AK. Znajduje się na budynku RCEZ, łącząc historię z edukacją młodzieży."
  },
  {
    id: 30,
    order_route: 30,
    name: "Miejsce Pamieci - Oboz w Skrobowie",
    era: "OKRES POWOJENNY",
    type: "MIEJSCE PAMIECI / OBOZ",
    addr: "Skrobow-Kolonia",
    coords: [22.5498, 51.4628],
    audio: "audio_oboz_w_skrobowie.mp3",
    bohater_naglowek: "Obóz Internowania w Skrobowie",
    bohater_kafelek: "Miejsce więzienia żołnierzy Armii Krajowej i podziemia niepodległościowego przetrzymywanych przez NKWD i UB po rozbrojeniu w 1944 roku."
  },
  {
    id: 31,
    order_route: 31,
    name: "Tablica AK i 27 WDP - Stacja PKP",
    era: "II WOJNA SWIATOWA",
    type: "MIEJSCE PAMIECI / TABLICA",
    addr: "ul. Dworcowa 1 (Stacja PKP Lubartów)",
    coords: [22.6152, 51.4655],
    audio: "audio_tablica_pkp_lubartow.mp3",
    bohater_naglowek: "Żołnierze AK i 27 WDP AK - Walki o PKP",
    bohater_kafelek: "Upamiętnienie walk o stację kolejową i wyzwolenie Lubartowa 22 lipca 1944 roku przez żołnierzy Armii Krajowej oraz 27 Wołyńskiej Dywizji Piechoty."
  },
  {
    id: 32,
    order_route: 32,
    name: "Symboliczna tablica ppor. Mirosława Orzechowskiego",
    era: "II WOJNA ŚWIATOWA",
    type: "MIEJSCE PAMIĘCI / TABLICA",
    addr: "Cmentarz Parafialny św. Anny w Lubartowie",
    coords: [22.602841, 51.462753],
    audio: "audio_orzechowski.mp3",
    bohater_naglowek: "ppor. pil. Mirosław Maciej Orzechowski (1916–1941)",
    bohater_kafelek: "Pilot Dywizjonu 308 'Krakowskiego', poległy w akcji bojowej nad Kanałem La Manche. Mogiła symboliczna na Cmentarzu Parafialnym w Lubartowie."
  }
];
