backend:
  name: git-gateway
  repo: bbandura091-lab/szlak--pamieci-karty
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/d304ccc3-7e0f-4e70-beb7-f7a7de8a3e48/pkce
  auth_token_endpoint: /sites/d304ccc3-7e0f-4e70-beb7-f7a7de8a3e48/token
  gateway_url: https://gateway.decapbridge.com

media_folder: "images"
public_folder: "images"

collections:
  - name: "nekropolia"
    label: "Nekropolia"
    folder: "content/nekropolia"
    create: true
    fields:
      - {label: "Imię i Nazwisko / Postać", name: "title", widget: "string"}
      - {label: "Rola / Stopień", name: "subtitle", widget: "string"}
      - {label: "Cmentarz / Lokacja", name: "badge", widget: "string"}
      - {label: "Zdjęcie", name: "image", widget: "image"}
      - {label: "Opis biograficzny", name: "body", widget: "markdown"}
